### ISSUE TITLE
Setup release-please to manage updating verisons of containers and packages

### ISSUE THREAD

**Issue by YrrepNoj** [defenseunicorns/leapfrogai#326] opened 2024-03-28 05:00 UTC
### Describe what should be investigated or refactored
This project has a lot of Dockerfiles and zarf.yaml configuration that we want to release in lock-step. Setup release please to help automate a lot of the work away.

---

NOTE: I am unsure if we can use JUST release-please when specifying the images we are including for our helm charts. We are currently managing this part with Zarf by using the ZARF_PKG_TMPL variables.
Before completly remove the PKG_TMPLs for release-please artifacts, please ensure we have a way to build & test local changes without having to either
1) Manually change versions in the zarf.yaml / values.yaml temporarily to build the test package
OR
2) Creating (and publishing locally) a new version of the image/package that are distinctly different from the upstream versions with the same tag.

**Comment by gregclark-defenseunicorns** [comment] 2024-08-26 20:04
Duplicate of https://github.com/defenseunicorns/leapfrogai/issues/696

**Closed** 2024-08-26 20:05 UTC
Labels: tech-debt
