### ISSUE TITLE
Determine acceptable Supabase resource limits

### ISSUE THREAD

**Issue by CollectiveUnicorn** [defenseunicorns/leapfrogai#459] opened 2024-04-29 19:55 UTC
### Describe what should be investigated or refactored
Determine appropriate resource limits for all Supabase components. The requests do not need to be specified but the limits should be set to ensure that all the cluster's resources are not eaten up by any Supabase component(s). The resource limits can be set in `bitnami-values.yaml`.

**Comment by YrrepNoj** [comment] 2024-05-06 18:51
Closing as a duplicate of #455

**Closed by YrrepNoj** 2024-05-06 18:51 UTC
Labels: tech-debt 💳, blocked :stop_sign:
