### ISSUE TITLE
spike: Experiment with different default resource limits & requests values for current models

### ISSUE THREAD

**Issue by YrrepNoj** [defenseunicorns/leapfrogai#327] opened 2024-03-28 05:50 UTC
We currently are not setting any CPU & GPU resource limits and requests within our deployments. Perform a quick experiment and come up with values that can serve as the default within our helm chart.

**Comment by gregclark-defenseunicorns** [comment] 2024-08-26 20:06
Duplicate of #816

**Closed** 2024-08-26 20:06 UTC
Labels: tech-debt
