### ISSUE TITLE
Log out button doesn't log me out

### ISSUE THREAD

**Issue by RothAndrew** [defenseunicorns/leapfrogai#536] opened 2024-05-17 15:34 UTC
### Environment
https://ai.burning.boats

### Steps to reproduce
1. Navigate to https://ai.burning.boats
2. Click "Log In with UDS SSO"
3. Click "Or sign in with: Google SSO"
4. Sign in with google creds
5. Click profile button in top right corner
6. Click "Log Out"
7. Click "Log In with UDS SSO"

### Expected result
I am again prompted to log in with my credentials

### Actual Result
I am immediately logged back into the LFAI app, which means my creds got cached even after clicking the log out button

### Visual Proof (screenshots, videos, text, etc)
![Kapture 2024-05-17 at 08 32 57](https://github.com/defenseunicorns/leapfrogai/assets/16000938/c7fc8cc4-2905-4635-9796-dfbfe3f252da)

### Severity/Priority
?

### Additional Context
none

**Comment by andrewrisse** [comment] 2024-07-11 18:23
the logout button logs you out of supabase, but your sso.uds.dev cookies are still valid, so when you log back in, it uses those cookies and doesn't make you re-enter your login.

You are logged out of leapfrog, but not logged out of keycloak.

closing as it is a duplicate of #526

**Closed by andrewrisse** 2024-07-11 18:23 UTC
Labels: possible-bug 🐛
