### ISSUE TITLE
api: run integration tests in e2e pipeline

### ISSUE THREAD

**Issue by gphorvath** [defenseunicorns/leapfrogai#534] opened 2024-05-16 22:08 UTC
### Describe what should be investigated or refactored
As we start to merge Files, Assistants, Vector Stores, etc. there are several tests that query the endpoints and check to see if the operations succeed on a running instance of Supabase. Ideally these would get run in a pipeline so we know they are passing before merging.

**Comment by justinthelaw** [comment] 2024-09-04 14:22
Duplicate of #564 , Supabase runs in E2E tests.

**Closed by justinthelaw** 2024-09-04 14:22 UTC
Labels: tech-debt
